<?php

/**
 * BaseSection
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $url_name
 * @property string $cover_img
 * @property boolean $publish
 * @property Doctrine_Collection $Categories
 * 
 * @method string              getTitle()      Returns the current record's "title" value
 * @method string              getUrlName()    Returns the current record's "url_name" value
 * @method string              getCoverImg()   Returns the current record's "cover_img" value
 * @method boolean             getPublish()    Returns the current record's "publish" value
 * @method Doctrine_Collection getCategories() Returns the current record's "Categories" collection
 * @method Section             setTitle()      Sets the current record's "title" value
 * @method Section             setUrlName()    Sets the current record's "url_name" value
 * @method Section             setCoverImg()   Sets the current record's "cover_img" value
 * @method Section             setPublish()    Sets the current record's "publish" value
 * @method Section             setCategories() Sets the current record's "Categories" collection
 * 
 * @package    NuevasFormas
 * @subpackage model
 * @author     Danilo R. Frid
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSection extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('section');
        $this->hasColumn('title', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 100,
             ));
        $this->hasColumn('url_name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 100,
             ));
        $this->hasColumn('cover_img', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('publish', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Category as Categories', array(
             'local' => 'id',
             'foreign' => 'section_id'));

        $sortable0 = new Doctrine_Template_Sortable();
        $this->actAs($sortable0);
    }
}