<?php

/**
 * BaseCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * @property string $cover_img
 * @property boolean $publish
 * @property integer $section_id
 * @property Section $Section
 * @property Doctrine_Collection $Models
 * 
 * @method string              getName()        Returns the current record's "name" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method string              getCoverImg()    Returns the current record's "cover_img" value
 * @method boolean             getPublish()     Returns the current record's "publish" value
 * @method integer             getSectionId()   Returns the current record's "section_id" value
 * @method Section             getSection()     Returns the current record's "Section" value
 * @method Doctrine_Collection getModels()      Returns the current record's "Models" collection
 * @method Category            setName()        Sets the current record's "name" value
 * @method Category            setDescription() Sets the current record's "description" value
 * @method Category            setCoverImg()    Sets the current record's "cover_img" value
 * @method Category            setPublish()     Sets the current record's "publish" value
 * @method Category            setSectionId()   Sets the current record's "section_id" value
 * @method Category            setSection()     Sets the current record's "Section" value
 * @method Category            setModels()      Sets the current record's "Models" collection
 * 
 * @package    NuevasFormas
 * @subpackage model
 * @author     Danilo R. Frid
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category');
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 100,
             ));
        $this->hasColumn('description', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('cover_img', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('publish', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('section_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Section', array(
             'local' => 'section_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasMany('Gallery as Models', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'name',
             ),
             'canUpdate' => true,
             ));
        $sortable0 = new Doctrine_Template_Sortable();
        $this->actAs($sluggable0);
        $this->actAs($sortable0);
    }
}