<?php

/**
 * Category
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    NuevasFormas
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Category extends BaseCategory
{
  public function getSortedModels() {
/*
    $models = Doctrine_Query::create()
      ->from('Model m')
      ->where('m.category_id = ?', $this->id)
      ->andWhere('m.publish = ?', true)
      ->orderBy('m.position asc')
      ->execute();
    return $models;
*/
    $galleries = Doctrine_Query::create()
      ->from('Gallery g')
      ->where('g.category_id = ?', $this->id)
      ->andWhere('g.publish = ?', true)
      ->orderBy('g.position asc')
      ->execute();
    return $galleries;
  }
}
