<?php

/**
 * ModelImageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModelImageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModelImageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ModelImage');
    }
}