<?php

/**
 * BaseGallery
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $category_id
 * @property string $title
 * @property string $cover_img
 * @property string $description
 * @property integer $price
 * @property boolean $publish
 * @property boolean $promote
 * @property Category $Category
 * @property Doctrine_Collection $Photos
 * 
 * @method integer             getCategoryId()  Returns the current record's "category_id" value
 * @method string              getTitle()       Returns the current record's "title" value
 * @method string              getCoverImg()    Returns the current record's "cover_img" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method integer             getPrice()       Returns the current record's "price" value
 * @method boolean             getPublish()     Returns the current record's "publish" value
 * @method boolean             getPromote()     Returns the current record's "promote" value
 * @method Category            getCategory()    Returns the current record's "Category" value
 * @method Doctrine_Collection getPhotos()      Returns the current record's "Photos" collection
 * @method Gallery             setCategoryId()  Sets the current record's "category_id" value
 * @method Gallery             setTitle()       Sets the current record's "title" value
 * @method Gallery             setCoverImg()    Sets the current record's "cover_img" value
 * @method Gallery             setDescription() Sets the current record's "description" value
 * @method Gallery             setPrice()       Sets the current record's "price" value
 * @method Gallery             setPublish()     Sets the current record's "publish" value
 * @method Gallery             setPromote()     Sets the current record's "promote" value
 * @method Gallery             setCategory()    Sets the current record's "Category" value
 * @method Gallery             setPhotos()      Sets the current record's "Photos" collection
 * 
 * @package    NuevasFormas
 * @subpackage model
 * @author     Danilo R. Frid
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGallery extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gallery');
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('cover_img', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4000,
             ));
        $this->hasColumn('price', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('publish', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('promote', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Category', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasMany('Photos', array(
             'local' => 'id',
             'foreign' => 'gallery_id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'title',
             ),
             ));
        $sortable0 = new Doctrine_Template_Sortable(array(
             'uniqueBy' => 
             array(
              0 => 'category_id',
             ),
             ));
        $this->actAs($sluggable0);
        $this->actAs($sortable0);
    }
}