generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Section
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          section
    with_doctrine_route:   true
    actions_base_class:    sfActions
    css:                   false

    config:
      actions: ~
      fields:
        title:     { label: Título }
        url_name:  { label: Nombre URL }
        cover_img: { label: Imagen Portada }
        position:  { label: Orden }
        publish:   { label: Publicar }
      list:
        title: Listado de Secciones
        sort: [ position, asc ]
      filter:  ~
      form:    ~
      edit:
        title: Editando Sección: %%title%%
      new:
        title: Alta de Sección
