<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version4 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addIndex('model', 'model_position_sortable', array(
             'fields' => 
             array(
              0 => 'position',
              1 => 'category_id',
             ),
             'type' => 'unique',
             ));
    }

    public function down()
    {
        $this->removeIndex('model', 'model_position_sortable', array(
             'fields' => 
             array(
              0 => 'position',
              1 => 'category_id',
             ),
             'type' => 'unique',
             ));
    }
}