<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version9 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('category', 'category_section_id_section_id', array(
             'name' => 'category_section_id_section_id',
             'local' => 'section_id',
             'foreign' => 'id',
             'foreignTable' => 'section',
             'onUpdate' => '',
             'onDelete' => 'RESTRICT',
             ));
        $this->addIndex('category', 'category_section_id', array(
             'fields' => 
             array(
              0 => 'section_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('category', 'category_section_id_section_id');
        $this->removeIndex('category', 'category_section_id', array(
             'fields' => 
             array(
              0 => 'section_id',
             ),
             ));
    }
}